inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.5,5.5],[-0.5,5.5],[-0.5,3.0]]
  marching_cubes_bound: [[-0.5,5.5],[-0.5,5.5],[-0.5,3.0]]
data:
  dataset: scannet
  input_folder: Datasets/scannet/scans/scene0012_00
  output: output/scannet/scans/scene0012_00
  id: 12
