inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[0.6,5.2],[0.0,5.6],[0.1,3.4]] #[[0.0,5.5],[0.0,6.0],[-0.5,3.5]]
  marching_cubes_bound: [[0.6,5.2],[0.0,5.6],[0.1,3.4]] #[[0.0,5.5],[0.0,6.0],[-0.5,3.5]]
data:
  dataset: scannet
  input_folder: Datasets/scannet/scans/scene0002_00
  output: output/scannet/scans/scene0002_00
  id: 02
