inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.5,3.0],[-0.5,7.5],[0.0,2.5]]
  marching_cubes_bound: [[-0.5,3.0],[-0.5,7.5],[0.0,2.5]]
data:
  dataset: scannet
  input_folder: Datasets/scannet/scans/scene0084_00
  output: output/scannet/scans/scene0084_00
  id: 84
