sync_method: strict
scale: 1
verbose: True
occupancy: True
low_gpu_mem: True
grid_len:
  low: 0.32 
  high: 0.16
  color: 0.16
  bound_divisible: 0.32
pretrained_decoders:
  low_high: pretrained/low_high.pt # one ckpt contain both low and high
meshing:
  level_set: 0
  resolution: 256 # change to 512 for higher resolution geometry
  eval_rec: False
  clean_mesh: True
  depth_test: False
  clean_mesh_bound_scale: 1.02
  get_largest_components: False
  color_mesh_extraction_method: direct_point_query
  remove_small_geometry_threshold: 0.2
tracking:
  ignore_edge_W: 20
  ignore_edge_H: 20
  use_color_in_tracking: True
  device: "cuda:0"
  handle_dynamic: True
  vis_freq: 50
  vis_inside_freq: 25
  w_color_loss: 0.5
  seperate_LR: False
  const_speed_assumption: True
  no_vis_on_first_frame: True
  gt_camera: True #False
  lr: 0.001
  pixels: 200
  iters: 10
mapping:
  device: "cuda:0"
  color_refine: True
  low_iter_ratio: 0.4
  high_iter_ratio: 0.6
  every_frame: 5
  fix_high: True
  fix_color: False
  no_vis_on_first_frame: True
  no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 50
  vis_inside_freq: 25 #each iteration 
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  w_color_loss: 0.2
  frustum_feature_selection: True
  keyframe_selection_method: 'overlap'
  save_selected_keyframes_info: False
  lr_first_factor: 5
  lr_factor: 1
  pixels: 1000
  iters_first: 1500
  iters: 60 
  stage:
    low:
      mlp_lr: 0.0
      decoders_lr: 0.0
      low_lr: 0.1
      high_lr: 0.0
      color_lr: 0.0
    high:
      mlp_lr: 0.005
      decoders_lr: 0.0
      low_lr: 0.005
      high_lr: 0.005
      color_lr: 0.0
    color:
      mlp_lr: 0.005
      decoders_lr: 0.005
      low_lr: 0.005 
      high_lr: 0.005 
      color_lr: 0.005 
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  N_samples: 32
  N_surface: 16
  N_importance: 0
  lindisp: False
  perturb: 0.0
data:
  dim: 3
model:
  c_dim: 32
  pos_embedding_method: fourier
